# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonexam_app', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='who',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
